### ISSUE TITLE
Test fails in podman, but the github action succeeds

### ISSUE THREAD

**Issue by dcermak** [os-autoinst/os-autoinst-distri-example#6]
See for instance: https://github.com/os-autoinst/os-autoinst-distri-example/runs/1459597974?check_suite_focus=true

The log states that the run failed:
```
[2020-11-26T15:08:23.011 UTC] [debug] >>> testapi::_check_backend_response: match=bootloader timed out after 30 (assert_screen)
[2020-11-26T15:08:23.092 UTC] [info] ::: basetest::runtest: # Test died: no candidate needle with tag(s) 'bootloader' matched
```
but the github action is marked as succeeded. I guess that's a bug?

**Comment by okurz** [comment]
No, that is so far intended. isotovideo gives an exit status of 0 if the test could be successfully conducted, i.e. not incomplete or crashed in the middle. Still the result would need to be checked. Especially here in this repository which does not have needles yet – because that is meant as the beginner user exercise – I consider it ok if the example CI run does not fail, also see https://github.com/os-autoinst/os-autoinst-distri-example/pull/4#issue-521201345 . Maybe I should explain that in the README?

**Comment by dcermak** [comment]
To be quite frank here: the CI will have a very limited use, if the openQA test itself fails but the CI is marked as green. Let's be real here: nearly no one checks the build logs of a successful CI run. So imho it would be really beneficial for the CI to be red if the openQA test fails, especially as this mode is lacking the openQA webui, making error spotting even harder.

If this is documented properly, then it could be acceptable. But I'd very much prefer it to actually fail the run.

**Comment by okurz** [comment]
Of course I agree that a CI is only helpful if the pipeline fails if the test fails but we should consider that this repo is an *example* repository. And I would like to prevent that visitors see the repo, see a failing badge on https://github.com/os-autoinst/os-autoinst-distri-example#example-distro-for-openqa- and stop looking further :)

So again, is it ok if we would just explain that in the README and explain what to do when someone wants to use the CI definition? Or do you have a better idea how I can make it obvious?

**Comment by dcermak** [comment]
Oliver Kurz <notifications@github.com> writes:

> Of course I agree that a CI is only helpful if the pipeline fails if the test fails but we should consider that this repo is an *example* repository. And I would like to prevent that visitors see the repo, see a failing badge on https://github.com/os-autoinst/os-autoinst-distri-example#example-distro-for-openqa- and stop looking further :)
>

Don't add the badge ;-) Or make the CI actually pass. Imho the latter
would be actually more useful here, as the user could already start from
a working example that they could just copy into their repo.

> So again, is it ok if we would just explain that in the README and explain what to do when someone wants to use the CI definition? Or do you have a better idea how I can make it obvious?

Then the example in the readme should however fail the CI pipeline if
the openQA test fails.

**Comment by okurz** [comment]
> Oliver Kurz <notifications@github.com> writes:
> Of course I agree that a CI is only helpful if the pipeline fails if the test fails but we should consider that this repo is an *example* repository. And I would like to prevent that visitors see the repo, see a failing badge on [os-autoinst/os-autoinst-distri-example#example-distro-for-openqa-](https://github.com/os-autoinst/os-autoinst-distri-example#example-distro-for-openqa-) and stop looking further :)
> Don't add the badge ;-) Or make the CI actually pass. Imho the latter would be actually more useful here, as the user could already start from a working example that they could just copy into their repo.

hm, how about in this example repository we add two pipelines, one passing showing "we can call isotovideo" and referencing that in the badge and one failing showing "this is what happens if an isotovideo failed as is expected"
